services:
  - type: web
    name: supabase-api
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    buildCommand: docker build -t supabase-api .
    startCommand: docker run -p 10000:8000 supabase-api
